\documentclass[11pt]{article}

\usepackage{amsmath}
\usepackage{hyperref}
\usepackage{fancyhdr}
\usepackage{amssymb}
\usepackage{geometry}
\usepackage{bm}
\usepackage{graphicx}
\usepackage{setspace}
\usepackage{multicol}
\usepackage{listings}

\onehalfspacing

\hypersetup{colorlinks=true, urlcolor=red, citecolor=blue, linkcolor=red}

\geometry{left=.9in, right=.9in, top=1.1in, bottom=1.1in}

<<pre, cache=FALSE, echo=FALSE, results='hide', warning=FALSE, message=FALSE>>=

source("~/GoogleDrive/Research/Fantasy/fantasy.Rprofile")

@

<<data, cache=TRUE, echo=FALSE, results='hide', warning=FALSE, message=FALSE>>=

week <- 15

load(paste0(d$fantasy, "week_", week, "_sims.Rda"))

# Team frequencies
team.freq <- teams %>%
  lapply(function(x) x[1:2]) %>%
  unlist %>%
  plyr::count(.) %>% 
  arrange(desc(freq)) %>%
  setNames(c("team", "freq")) %>%
  mutate(
    team.code = 1:n()
    )

# Player frequencies
dat$id.num <- 1:nrow(dat)
player.freq <- teams %>%
  lapply(function(x) x[1:2]) %>%
  unlist %>%
  sapply(function(x) strsplit(x, "-")) %>%
  unlist %>%
  plyr::count(.) %>%
  merge(dat[c("id.num", "name", "pos")], by.x = "x", by.y = "id.num") %>%
  arrange(pos, desc(freq))

@ 

\begin{document}
\thispagestyle{fancy}

\lhead{\Large{\bf{FanDuel - Week 15}}}

\noindent Here are the top ten teams for week \Sexpr{week} based on 500,000 simulations:

<<team_1, cache=TRUE, echo=FALSE>>=

dat %>%
  mutate(
    id.num = 1:n()
  ) %>%
  subset(id.num %in% unlist(strsplit(team.freq$team[1], "-"))) %>%
  select(pos, name, fd.salary, team, home) %>%
  arrange(pos)

@

<<team_2, cache=TRUE, echo=FALSE>>=

dat %>%
  mutate(
    id.num = 1:n()
  ) %>%
  subset(id.num %in% unlist(strsplit(team.freq$team[2], "-"))) %>%
  select(pos, name, fd.salary, team, home) %>%
  arrange(pos)
  
@

<<team_3, cache=TRUE, echo=FALSE>>=

dat %>%
  mutate(
    id.num = 1:n()
  ) %>%
  subset(id.num %in% unlist(strsplit(team.freq$team[3], "-"))) %>%
  select(pos, name, fd.salary, team, home) %>%
  arrange(pos)
  
@

<<team_4, cache=TRUE, echo=FALSE>>=

dat %>%
  mutate(
    id.num = 1:n()
  ) %>%
  subset(id.num %in% unlist(strsplit(team.freq$team[4], "-"))) %>%
  select(pos, name, fd.salary, team, home) %>%
  arrange(pos)
  
@

<<team_5, cache=TRUE, echo=FALSE>>=

dat %>%
  mutate(
    id.num = 1:n()
  ) %>%
  subset(id.num %in% unlist(strsplit(team.freq$team[5], "-"))) %>%
  select(pos, name, fd.salary, team, home) %>%
  arrange(pos)
  
@

<<team_6, cache=TRUE, echo=FALSE>>=

dat %>%
  mutate(
    id.num = 1:n()
  ) %>%
  subset(id.num %in% unlist(strsplit(team.freq$team[6], "-"))) %>%
  select(pos, name, fd.salary, team, home) %>%
  arrange(pos)
  
@

<<team_7, cache=TRUE, echo=FALSE>>=

dat %>%
  mutate(
    id.num = 1:n()
  ) %>%
  subset(id.num %in% unlist(strsplit(team.freq$team[7], "-"))) %>%
  select(pos, name, fd.salary, team, home) %>%
  arrange(pos)
  
@

<<team_8, cache=TRUE, echo=FALSE>>=

dat %>%
  mutate(
    id.num = 1:n()
  ) %>%
  subset(id.num %in% unlist(strsplit(team.freq$team[8], "-"))) %>%
  select(pos, name, fd.salary, team, home) %>%
  arrange(pos)
  
@

<<team_9, cache=TRUE, echo=FALSE>>=

dat %>%
  mutate(
    id.num = 1:n()
  ) %>%
  subset(id.num %in% unlist(strsplit(team.freq$team[9], "-"))) %>%
  select(pos, name, fd.salary, team, home) %>%
  arrange(pos)
  
@

<<team_10, cache=TRUE, echo=FALSE>>=

dat %>%
  mutate(
    id.num = 1:n()
  ) %>%
  subset(id.num %in% unlist(strsplit(team.freq$team[10], "-"))) %>%
  select(pos, name, fd.salary, team, home) %>%
  arrange(pos)
  
@

\noindent Figure \ref{team.freq} shows the relative frequency that each of the \Sexpr{nrow(team.freq)} optimal teams ended up winning.  Figure \ref{player.freq} shows the relative frequency for those players who belonged on the winning team at least 5\% of the time.

%------------------------------------------------------------------------------	
\newpage
\begin{figure}[!t]
\centering
\caption{Frequency distribution of optimal fantasy teams} \label{team.freq}
%\includegraphics[width=\textwidth]{../figures/team_freq_15.pdf}
<<team_freq, cache=TRUE, echo=FALSE, fig.width='\\textwidth'>>=

# Team frequency plot
ggplot(data = team.freq) +
  geom_bar(
    aes(x = factor(team.code, levels = rev(team.code)), y = freq / (2*iter)),
    stat = "identity",
    fill = "grey75",
    colour = "black") +
  coord_flip() +
  theme_classic() +
  labs(
    x = "Team",
    y = "Frequency") +
  theme(
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    axis.title.x = element_text(vjust = 0),
    axis.title.y = element_text(vjust = 1)
    )

@
\end{figure}
%------------------------------------------------------------------------------

%------------------------------------------------------------------------------	
\newpage
\begin{figure}[!t]
\centering
\caption{Frequency distribution of optimal fantasy players} \label{player.freq}
%\includegraphics[width=\textwidth]{../figures/player_freq_15.pdf}
<<player_freq, cache=TRUE, echo=FALSE, out.width='\\textwidth'>>=
 
# Player frequency plot
ggplot(data = subset(player.freq, freq / (2*iter) >= 0.05)) +
  geom_bar(
    aes(x = factor(name, levels = rev(name)), y = freq / (2*iter), fill = pos),
    stat = "identity",
    colour = "black") +
  scale_fill_manual(
    name = "Position",
    values = paste0("grey", seq(20, 100, length.out = 6))) +
  coord_flip() +
  theme_classic() +
  labs(
    x = "Player",
    y = "Frequency") +
  theme(
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    axis.title.x = element_text(vjust = 0),
    axis.title.y = element_text(vjust = 1),
    legend.position = c(0.90, 0.80))

@
\end{figure}
%------------------------------------------------------------------------------

\end{document} 